image: docker:stable
#image: mcr.microsoft.com/dotnet/core/sdk:2.2.301
#image: crunchtime/dotnetcore-nuget-msbuild-docker

services:
  - docker:dind

before_script:
  - docker info


build:
  only:
    - master
  before_script:
    - docker login registry.gitlab.com -u "bigyantest" -p "@Test@123"
  script:
    - docker build -t registry.gitlab.com/bigyantest/testkdotnetcore02 .
  after_script:
    - docker logout ${CI_REGISTRY}
  stage: build
  tags:
    - docker
