image : microsoft/dotnet:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - dotnet build
    
deploy_mysolution:
  stage: deploy
  image:
    name: microsoft/dotnet:latest
  script:
    - dotnet build
    - PKGPATH=$(find /builds/bigyantest/testkdotnetcore02/TestKSdkCore/bin/Debug/*.nupkg)
    - dotnet nuget push $PKGPATH -k $NUGET_PUSH_KEY -s https://www.nuget.org/
  only:
    - master
